export const FETCH_CARDS_REQUEST = 'FETCH_CARDS_REQUEST'
export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS'
export const FETCH_CARDS_FAIL = 'FETCH_CARDS_FAIL'

export const FETCH_DRAWCARD_REQUEST = 'FETCH_DRAWCARD_REQUEST'
export const FETCH_DRAWCARD_SUCCESS = 'FETCH_DRAWCARD_SUCCESS'
export const FETCH_DRAWCARD_FAIL = 'FETCH_DRAWCARD_FAIL'

export const RESET_GAME = 'RESET_GAME'
export const PLACE_BET = 'PLACE_BET'
export const BALANCE_WIN = 'BALANCE_WIN'
export const BALANCE_LOOSE = 'BALANCE_LOOSE'
export const GAME_STATUS = 'GAME_STATUS'
export const NEW_GAME = 'NEW_GAME'